# Generated by Django 5.0.3 on 2025-09-05 19:02

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='id',
            field=models.CharField(default=authentication.models.generate_verify_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='id',
            field=models.CharField(default=authentication.models.generate_pending_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=authentication.models.generate_user_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
