# Generated by Django 5.0.3 on 2025-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_referral_and_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 – Beginner'), ('A2', 'A2 – Elementary'), ('B1', 'B1 – Intermediate'), ('B2', 'B2 – Upper-Intermediate'), ('C1', 'C1 – Advanced')], max_length=3, null=True),
        ),
    ]
