# Generated by Django 5.2.6 on 2026-01-15 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubscriptionOnboarding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_key', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Annual')], max_length=10, null=True)),
                ('reason', models.CharField(blank=True, choices=[('exercise_mind', 'Exercise my mind'), ('travel', 'Prepare for travel'), ('career', 'Boost my professional career'), ('fun', 'For fun'), ('studies', 'Enhance studies'), ('connect', 'Connect with people'), ('other', 'Other')], max_length=30, null=True)),
                ('reason_other', models.TextField(blank=True, null=True)),
                ('daily_goal', models.CharField(blank=True, choices=[('15', '15 minutes per day'), ('30', '30 minutes per day'), ('60', '1 hour per day')], max_length=2, null=True)),
                ('spanish_knowledge', models.CharField(blank=True, choices=[('starting', 'I am just starting to learn'), ('common_words', 'I know some common words'), ('simple_conversations', 'I can have simple conversations'), ('several_topics', 'I can converse on several topics'), ('debate', 'I can debate in detail on most topics')], max_length=30, null=True)),
                ('start_preference', models.CharField(blank=True, choices=[('beginning', 'From the beginning'), ('discover', 'Discover my level')], max_length=15, null=True)),
                ('test_answers', models.JSONField(blank=True, null=True)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('suggested_level', models.CharField(blank=True, choices=[('A1', 'A1 – Beginner'), ('A2', 'A2 – Elementary'), ('B1', 'B1 – Intermediate'), ('B2', 'B2 – Upper-Intermediate'), ('C1', 'C1 – Advanced')], max_length=3, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
