# Generated by Django 5.0.3 on 2025-12-06 13:41

import django.db.models.deletion
import django.utils.timezone
import lessons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(default=lessons.models.generate_lesson_id, max_length=50, primary_key=True, serialize=False)),
                ('block', models.CharField(choices=[('A1', 'A1 – Beginner'), ('A2', 'A2 – Basic'), ('B1', 'B1 – Intermediate'), ('B2', 'B2 – Upper Intermediate'), ('C1', 'C1 – Advanced')], max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Vocabulary', 'Vocabulary'), ('Speech', 'Speech'), ('Listening', 'Listening'), ('Reading', 'Reading'), ('Grammar', 'Grammar'), ('Writing', 'Writing'), ('Pronunciation', 'Pronunciation'), ('Conversation', 'Conversation')], max_length=50)),
                ('file', models.FileField(upload_to='lesson_parts/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='lessons.lesson')),
            ],
        ),
    ]
