# Generated by Django 5.0.3 on 2026-03-11 07:04

import django.db.models.deletion
import django.utils.timezone
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=notifications.models.generate_notification_id, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('general', 'General'), ('alert', 'Alert'), ('course', 'Course'), ('system', 'System')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cta_label', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('audience_mode', models.CharField(choices=[('all', 'All users'), ('filtered', 'Filtered users'), ('selected', 'Selected users')], default='all', max_length=20)),
                ('audience_filters', models.JSONField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivered_at'],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
