# Generated by Django 5.0.3 on 2026-03-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience_user_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
