# Generated by Django 5.0.3 on 2026-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_audience_user_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='audience_mode',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='audience_user_ids',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
